-- master

-- USUARIO 1
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER US_UNO IDENTIFIED BY US_UNO
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER US_UNO QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO US_UNO;
GRANT CREATE TABLE TO US_UNO;
GRANT CREATE SYNONYM TO US_UNO;
GRANT CREATE PUBLIC SYNONYM TO US_UNO;
GRANT CREATE SEQUENCE TO US_UNO;




GRANT rol_optimizador TO US_UNO;
ALTER USER US_UNO DEFAULT ROLE "ROL_OPTIMIZADOR";





-- USUARIO 2
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER US_DOS IDENTIFIED BY US_DOS
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
GRANT CREATE SESSION TO US_DOS;
GRANT SELECT ON syn_cliente TO US_DOS;
GRANT SELECT ON syn_a_camion TO US_DOS;
GRANT SELECT ON US_UNO.syn_comuna TO US_DOS;
GRANT CREATE VIEW TO US_DOS;




-- ROLES Y PERMISOS
CREATE ROLE rol_optimizador;
GRANT CREATE TRIGGER TO rol_optimizador;
GRANT CREATE ANY INDEX TO rol_optimizador;
--GRANT DROP ANY INDEX TO rol_optimizador;

