--user 1

ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER ANYELOWEKO IDENTIFIED BY ANYELOWEKO
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER ANYELOWEKO QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO ANYELOWEKO ;
GRANT "CONNECT" TO ANYELOWEKO ;
ALTER USER ANYELOWEKO DEFAULT ROLE "RESOURCE","CONNECT";

GRANT CREATE VIEW TO ANYELOWEKO;
GRANT CREATE SYNONYM TO ANYELOWEKO;
GRANT CREATE PUBLIC SYNONYM TO ANYELOWEKO;






--user 2

ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER ANGELOXD IDENTIFIED BY ANGELOXD
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER ANGELOXD QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO ANGELOXD ;
GRANT "CONNECT" TO ANGELOXD ;
ALTER USER ANGELOXD DEFAULT ROLE "RESOURCE","CONNECT";

GRANT SELECT ON s_departamentos TO ANGELOXD;
GRANT SELECT ON ANYELOWEKO.s_paises TO ANGELOXD;
GRANT SELECT ON ANYELOWEKO.s_empleados TO ANGELOXD;
GRANT UPDATE ON ANYELOWEKO.s_empleados TO ANGELOXD;


-- ROLES
CREATE ROLE rol_nashe;

GRANT CREATE SESSION TO rol_nashe;
GRANT CREATE VIEW TO rol_nashe;
GRANT SELECT ON ANYELOWEKO.s_empleados TO rol_nashe;

GRANT rol_nashe TO ANGELOXD;
ALTER USER ANGELOXD DEFAULT ROLE "ROL_NASHE";
